# Default values for domino.

image:
  # -- Name of the Domino server container image
  name: hclcom/domino
  # -- Tag of the Domino server container image (usually a version number or "latest")
  tag: latest
  imageCredentials:
    # -- Hostname of a private container registry
    registry: registry.example.com
  # -- When should be image pulled from the registry: "Always", "IfNotPresent", "Never"
  imagePullPolicy: IfNotPresent

domino:
  server:
    # -- Server type ("first" or "additional" )
    type: first
    # -- Server common name ("Domino" in "Domino/DemoOrg @ DemoDomain")
    name: Domino
    # -- Domain name ("DemoDomain" in "Domino/DemoOrg @ DemoDomain")
    domainName: DemoDomain
    # -- Server title (description)
    serverTitle: Demo Server
    # -- Set "true" if you want to use existing server.id
    useExistingServerID: false
    # -- Server ID filename. Used when useExistingServerID = true.
    idFileName: server.id
  network:
    # -- Server DNS host name
    hostName: domino.example.com
  org:
    # -- Organization name ("DemoOrg" in "Domino/DemoOrg @ DemoDomain")
    orgName: DemoOrg
    # -- Set "true" if you want to use existing certr.id
    useExistingCertifierID: false
    # -- Cert ID filename. Used when useExistingCertifierID = true.
    idFileName: cert.id
    # -- Cert ID password
    certifierPassword: SecretOrgPassw0rd
  admin:
    # -- Administrator first name
    firstName: Super
    # -- Administrator last name
    lastName: Admin
    # -- Set "true" if you want to use existing admin.id
    useExistingAdminID: false
    # -- Admin ID filename. Used when useExistingAdminID = true.
    idFileName: admin.id
    # -- Admin ID password
    password: SecretAdminPassw0rd
  idVault:
    # -- ID Vault password
    idPassword: SecretVaultPassw0rd
  appConfiguration:
    # -- Name of the form that should be used as a login form in domcfg.nsf
    webLoginForm: DWALoginForm
    # -- Filename of the NSF database that where the webLoginForm is stored
    webLoginFormDB: iwaredir.nsf

install:
    # -- Path to local ID files. Used when you set true in reusing Server ID, Cert ID or Admin ID.
    # idsLocalDir: "ids"
  # -- Path in a pod where IDs are mounted during the pod creation
  idsMountedDir: /local/ids
  # -- Path in a pod where IDs are copied from a mounted directory
  idsDir: /tmp
  # -- Set "true" when you want to keep existing IDs mounted to the pod. 
  # Set "false" when you do not want mount existing IDs to the pod anymore. 
  # Tip: use "true" during the first setup, then change to "false".
  mountIds: false
  # -- Path (filesystem or URL) to a zip file that will be downloaded and extracted into the dominodata directory
  CustomNotesdataZip: ""

pod:
  # -- If set, Domino is deployed only to the node that matches the label. Example: "domino: castor"
  nodeSelector: {}

logs:
  # -- Send Domino console log to the pod's standard output (so it could be read using kubectl logs)
  dominoStdOut: "yes"

service:
  # -- Should some ports be exposed outside of the cluster (by exposing the port, not through Ingress controller)?
  enabled: false
  # -- Service type ("LoadBalancer" or "ClusterIP")
  type: LoadBalancer
  # -- Used only when service.type = ClusterIP. IP where the service should be exposed.
  externalIP: 10.20.30.40
  http:
    # -- Should HTTP be exposed directly?
    expose: false
    # -- Number of exposed HTTP port (probably NOT 80, because it is usually occupied by Ingress Controller service)
    port: 3080
  https:
    # -- Should HTTPS be exposed directly?
    expose: false
    # -- Number of exposed HTTP port (probably NOT 443, because it is usually occupied by Ingress Controller service)
    port: 3443
  nrpc:
    # -- Should NRPC be exposed directly?
    expose: false
    # -- Number of exposed NRPC port (could be 1352)
    port: 1352
  nomad:
    # -- Should Nomad be exposed directly?
    expose: false
    # -- Number of exposed Nomad port (could be 1352)
    port: 9443

ingress:
  # -- Should Domino HTTP traffic be exposed through Ingress Controller?
  enabled: true
  # -- Enable TLS in Ingress Rule? (If "true", Ingress wil provide handle TLS communication with the clients.)
  tls: false
  # -- Ingress class. Must match "kubectl get ingressclass".
  class: nginx
  # -- Should Ingress Rule ise Let's Encrypt as a Certificate Issuer?
  letsEncryptEnabled: false
  nomad:
    # -- Should Nomad Web traffic be exposed through Ingress Controller? (It requires a dedicated hostname.)
    enabled: false
    # -- Hostname for Nomad web access (Usually different than a hostname for a classic Domino HTTP access.)
    hostname: domino-nomad.example.com

certManager:
  # -- Should ClusterIssuer resource for Let's Encrypt be crearted?
  createIssuer: true
  # -- Type of Let's Encrypt certificate authority ("staging" or "prod")
  leCertificate: staging
  # -- Email used when creating a profile for Let's Encrypt
  leEmail: name@example.com

persistence:
  # -- Should dominodata volume be persistent?
  # Warning: if you specify "false", your Domino data will be DELETED each time you restart the pod!
  enabled: false
  # -- Specify the StorageClass used to provision the volume. Must be one of the classes in "kubectl get storageclass". 
  # If not specified, a default StorageClass is used (if exists).
  storageClass: ''
  # -- Size of the data volume (/local/notesdata)
  size: 4Gi